// Список внутриигровых тестов: каждый новый файл *.test.ts в src/test/ добавляется сюда.
import "./demo.test"
import "./automaton.test"
import "./registry.test"
import "./movement.test"
import "./appearance.test"
import "./cargo.test"
import "./actions.test"
import "./mining.test"
import "./transfer.test"
import "./handling.test"
import "./inspect.test"
import "./energy.test"
